/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SEPackage;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Rajendra
 */
class Snake{
    public int head;
    public int tail;
    public Snake(int h,int t)
    {
        head=h;
        tail=t;
    }
}
class Ladder{
    public int top;
    public int bottom;
    public Ladder(int t,int b)
    {
        top=t;
        bottom=b;
    }
}
class Customize{
    public ArrayList<Snake>snakes=new ArrayList();
    public ArrayList<Ladder>ladders=new ArrayList();
    public int players;
    public int size;
    public int HighScore;
    public boolean isCustomized;
    public Customize(int snake,int ladder,int tablesize,int hs)
    {
        while(snakes.size()!=0)
            snakes.remove(0);
        while(ladders.size()!=0)
            ladders.remove(0);
        players=0;
        size=tablesize;
        HighScore=hs;
        isCustomized=false;
    }
}
class Player{
        public ImageIcon pImg;
	public String name;
	public int currentPos;
	public int moves;
	
	public Player(int number)
	{
            currentPos=0;
            moves=0;
            String s="C:\\Users\\Rajendra\\Desktop\\snakeladder\\images\\player"+number+".png";
            File pFile = new File(s);
            String pPath = pFile.getAbsolutePath();
            pImg = new ImageIcon(pPath);
	}
}
public class StartGUI extends javax.swing.JFrame {
    public int choice=8;
    private Reader fr;
    private JPanel pan[],panel;
    private ImageIcon dice[]=null;
    private ImageIcon ladderImage;
    private ImageIcon snakeImage;
    private JLabel label,label_1,label_2;
    private boolean pWin[];
    private Player player[];
    private int present;
    private boolean Dice;
    private int No;
    private Random random;
    private JLabel labelPlayer[],playerImage[][],labelDice;
    private JFrame game;
    
    /**
     * Creates new form StartGUI
     */
    public Customize cust=null;
    public StartGUI() {
        initComponents();
        StartPanel.setVisible(false);
        SettingPanel.setVisible(false);
        Player1.setVisible(false);
        Player2.setVisible(false);
        Player3.setVisible(false);
        HighScorePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HighScorePanel = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        HighScoreField = new javax.swing.JTextField();
        HighScoreLabel = new javax.swing.JLabel();
        PlayPanel = new javax.swing.JPanel();
        Play = new javax.swing.JLabel();
        Help = new javax.swing.JLabel();
        HighScore = new javax.swing.JLabel();
        HoverBar = new javax.swing.JTextField();
        Bg = new javax.swing.JLabel();
        StartPanel = new javax.swing.JPanel();
        Back1 = new javax.swing.JButton();
        EnterSetting = new javax.swing.JButton();
        StartButton = new javax.swing.JLabel();
        NumberPlayers = new javax.swing.JComboBox();
        BgPlayEnter = new javax.swing.JLabel();
        SettingPanel = new javax.swing.JPanel();
        MusicButton = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        SettingsBg = new javax.swing.JLabel();
        StartLadder = new javax.swing.JTextField();
        EndLadder = new javax.swing.JTextField();
        TailField = new javax.swing.JTextField();
        HeadField = new javax.swing.JTextField();
        SnakesPosition = new javax.swing.JLabel();
        LadderPosition = new javax.swing.JLabel();
        TableSize = new javax.swing.JLabel();
        LadderPane = new javax.swing.JScrollPane();
        LadderArea = new javax.swing.JTextArea();
        LadderGo = new javax.swing.JButton();
        LadderBg = new javax.swing.JLabel();
        SnakePane = new javax.swing.JScrollPane();
        SnakeArea = new javax.swing.JTextArea();
        SnakeGo = new javax.swing.JButton();
        SnakeBg = new javax.swing.JLabel();
        button5 = new javax.swing.JRadioButton();
        button6 = new javax.swing.JRadioButton();
        button7 = new javax.swing.JRadioButton();
        button8 = new javax.swing.JRadioButton();
        button9 = new javax.swing.JRadioButton();
        button10 = new javax.swing.JRadioButton();
        button11 = new javax.swing.JRadioButton();
        button12 = new javax.swing.JRadioButton();
        TableBg = new javax.swing.JLabel();
        Player1 = new javax.swing.JPanel();
        Players1Name1 = new javax.swing.JTextField();
        Play1 = new javax.swing.JLabel();
        Back2 = new javax.swing.JButton();
        Players1 = new javax.swing.JLabel();
        Player2 = new javax.swing.JPanel();
        Play2 = new javax.swing.JLabel();
        Back4 = new javax.swing.JButton();
        Players2Name1 = new javax.swing.JTextField();
        Players2Name2 = new javax.swing.JTextField();
        Players2 = new javax.swing.JLabel();
        Player3 = new javax.swing.JPanel();
        Play3 = new javax.swing.JLabel();
        Back3 = new javax.swing.JButton();
        Name1 = new javax.swing.JTextField();
        Name2 = new javax.swing.JTextField();
        Name3 = new javax.swing.JTextField();
        Players3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(480, 360));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HighScorePanel.setAlignmentX(0.0F);
        HighScorePanel.setAlignmentY(0.0F);
        HighScorePanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        HighScorePanel.setMinimumSize(new java.awt.Dimension(480, 360));
        HighScorePanel.setPreferredSize(new java.awt.Dimension(480, 360));
        HighScorePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/back.jpg"))); // NOI18N
        Back.setText("jButton1");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        HighScorePanel.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        HighScoreField.setEditable(false);
        HighScoreField.setBackground(new java.awt.Color(204, 51, 0));
        HighScoreField.setForeground(new java.awt.Color(102, 0, 0));
        HighScoreField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HighScoreField.setText("Click to see");
        HighScoreField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HighScoreField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HighScoreField.setOpaque(false);
        HighScoreField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HighScoreFieldMouseClicked(evt);
            }
        });
        HighScoreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighScoreFieldActionPerformed(evt);
            }
        });
        HighScorePanel.add(HighScoreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 110, -1));

        HighScoreLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/HighScore.png"))); // NOI18N
        HighScorePanel.add(HighScoreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(HighScorePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        PlayPanel.setMinimumSize(new java.awt.Dimension(480, 360));
        PlayPanel.setPreferredSize(new java.awt.Dimension(480, 360));
        PlayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayMouseClicked(evt);
            }
        });
        Play.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PlayMouseMoved(evt);
            }
        });
        PlayPanel.add(Play, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 150, 32));

        Help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        Help.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HelpMouseMoved(evt);
            }
        });
        PlayPanel.add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 150, 30));

        HighScore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HighScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HighScoreMouseClicked(evt);
            }
        });
        HighScore.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                HighScoreMouseMoved(evt);
            }
        });
        PlayPanel.add(HighScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 130, 20));

        HoverBar.setEditable(false);
        HoverBar.setBackground(new java.awt.Color(102, 153, 0));
        HoverBar.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        HoverBar.setForeground(new java.awt.Color(0, 51, 0));
        HoverBar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HoverBar.setBorder(null);
        HoverBar.setOpaque(false);
        HoverBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoverBarActionPerformed(evt);
            }
        });
        PlayPanel.add(HoverBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 480, 20));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/snake-and-ladder-lite-screenshot-1.png"))); // NOI18N
        Bg.setAlignmentY(0.0F);
        PlayPanel.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PlayPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        StartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/back.jpg"))); // NOI18N
        Back1.setText("jButton1");
        Back1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        Back1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back1MouseClicked(evt);
            }
        });
        StartPanel.add(Back1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        EnterSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/images.jpg"))); // NOI18N
        EnterSetting.setText("jButton1");
        EnterSetting.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        EnterSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnterSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnterSettingMouseClicked(evt);
            }
        });
        StartPanel.add(EnterSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        StartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartButtonMouseClicked(evt);
            }
        });
        StartPanel.add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 120, 30));

        NumberPlayers.setBackground(new java.awt.Color(0, 51, 0));
        NumberPlayers.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        NumberPlayers.setForeground(new java.awt.Color(51, 0, 0));
        NumberPlayers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        NumberPlayers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        NumberPlayers.setOpaque(false);
        StartPanel.add(NumberPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 70, -1));

        BgPlayEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/sankes.png"))); // NOI18N
        StartPanel.add(BgPlayEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        SettingPanel.setAlignmentX(0.0F);
        SettingPanel.setAlignmentY(0.0F);
        SettingPanel.setMinimumSize(new java.awt.Dimension(480, 360));
        SettingPanel.setPreferredSize(new java.awt.Dimension(480, 360));
        SettingPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MusicButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SettingPanel.add(MusicButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 90));

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/bg.png"))); // NOI18N
        BackButton.setText("jLabel1");
        BackButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(51, 204, 0)));
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        SettingPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 90, 50));

        SettingsBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/Setting.png"))); // NOI18N
        SettingPanel.add(SettingsBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        StartLadder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StartLadder.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        StartLadder.setOpaque(false);
        SettingPanel.add(StartLadder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, -1));

        EndLadder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EndLadder.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EndLadder.setOpaque(false);
        EndLadder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndLadderActionPerformed(evt);
            }
        });
        SettingPanel.add(EndLadder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 100, -1));

        TailField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TailField.setOpaque(false);
        TailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TailFieldActionPerformed(evt);
            }
        });
        SettingPanel.add(TailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 100, -1));

        HeadField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        HeadField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        HeadField.setOpaque(false);
        SettingPanel.add(HeadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 90, 100, -1));

        SnakesPosition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SnakesPosition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SnakesPositionMouseClicked(evt);
            }
        });
        SettingPanel.add(SnakesPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, 20));

        LadderPosition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LadderPosition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LadderPositionMouseClicked(evt);
            }
        });
        SettingPanel.add(LadderPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 11, 130, 20));

        TableSize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TableSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSizeMouseClicked(evt);
            }
        });
        SettingPanel.add(TableSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 90, 20));

        LadderArea.setEditable(false);
        LadderArea.setColumns(20);
        LadderArea.setRows(5);
        LadderArea.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        LadderPane.setViewportView(LadderArea);

        SettingPanel.add(LadderPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 220));

        LadderGo.setText("Go!");
        LadderGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LadderGoMouseClicked(evt);
            }
        });
        LadderGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LadderGoActionPerformed(evt);
            }
        });
        SettingPanel.add(LadderGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        LadderBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/LadderPosition.png"))); // NOI18N
        LadderBg.setText("jLabel1");
        SettingPanel.add(LadderBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        SnakeArea.setEditable(false);
        SnakeArea.setColumns(20);
        SnakeArea.setRows(5);
        SnakeArea.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        SnakePane.setViewportView(SnakeArea);

        SettingPanel.add(SnakePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 220));

        SnakeGo.setText("Go!");
        SnakeGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SnakeGoMouseClicked(evt);
            }
        });
        SnakeGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnakeGoActionPerformed(evt);
            }
        });
        SettingPanel.add(SnakeGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        SnakeBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/SnakePosition.png"))); // NOI18N
        SnakeBg.setText("jLabel1");
        SettingPanel.add(SnakeBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        button5.setOpaque(false);
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
        });
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        SettingPanel.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        button6.setOpaque(false);
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
        });
        SettingPanel.add(button6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        button7.setOpaque(false);
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
        });
        SettingPanel.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        button8.setSelected(true);
        button8.setOpaque(false);
        button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button8MouseClicked(evt);
            }
        });
        SettingPanel.add(button8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 177, -1, -1));

        button9.setOpaque(false);
        button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button9MouseClicked(evt);
            }
        });
        SettingPanel.add(button9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 211, -1, -1));

        button10.setOpaque(false);
        button10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button10MouseClicked(evt);
            }
        });
        SettingPanel.add(button10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        button11.setOpaque(false);
        button11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button11MouseClicked(evt);
            }
        });
        SettingPanel.add(button11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        button12.setOpaque(false);
        button12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button12MouseClicked(evt);
            }
        });
        SettingPanel.add(button12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        TableBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/TableSize.png"))); // NOI18N
        TableBg.setText("jLabel1");
        SettingPanel.add(TableBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(SettingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        Player1.setMinimumSize(new java.awt.Dimension(480, 360));
        Player1.setPreferredSize(new java.awt.Dimension(480, 360));
        Player1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Player1MouseClicked(evt);
            }
        });
        Player1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Players1Name1.setBackground(new java.awt.Color(153, 0, 0));
        Players1Name1.setForeground(new java.awt.Color(255, 255, 255));
        Players1Name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Players1Name1.setText("Player1");
        Players1Name1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 0, 0), 1, true));
        Players1Name1.setOpaque(false);
        Player1.add(Players1Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 190, 140, 30));

        Play1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play1MouseClicked(evt);
            }
        });
        Player1.add(Play1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 130, 30));

        Back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/back.jpg"))); // NOI18N
        Back2.setText("jButton1");
        Back2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        Back2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back2MouseClicked(evt);
            }
        });
        Player1.add(Back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 90, 30));

        Players1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/Player1.png"))); // NOI18N
        Player1.add(Players1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        Player2.setMinimumSize(new java.awt.Dimension(480, 360));
        Player2.setPreferredSize(new java.awt.Dimension(480, 360));
        Player2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play2MouseClicked(evt);
            }
        });
        Player2.add(Play2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 140, 30));

        Back4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/back.jpg"))); // NOI18N
        Back4.setText("jButton1");
        Back4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        Back4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back4MouseClicked(evt);
            }
        });
        Player2.add(Back4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        Players2Name1.setBackground(new java.awt.Color(102, 0, 0));
        Players2Name1.setForeground(new java.awt.Color(255, 255, 255));
        Players2Name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Players2Name1.setText("Player1");
        Players2Name1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 1, true));
        Players2Name1.setOpaque(false);
        Player2.add(Players2Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 190, 140, 30));

        Players2Name2.setBackground(new java.awt.Color(0, 153, 51));
        Players2Name2.setForeground(new java.awt.Color(255, 255, 255));
        Players2Name2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Players2Name2.setText("Player2");
        Players2Name2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 51, 0), 1, true));
        Players2Name2.setOpaque(false);
        Player2.add(Players2Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 240, 150, 30));

        Players2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/Player2.png"))); // NOI18N
        Player2.add(Players2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        Player3.setMinimumSize(new java.awt.Dimension(480, 360));
        Player3.setPreferredSize(new java.awt.Dimension(480, 360));
        Player3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Play3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Play3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Play3MouseClicked(evt);
            }
        });
        Player3.add(Play3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 140, 30));

        Back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/back.jpg"))); // NOI18N
        Back3.setText("jButton1");
        Back3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 153, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(51, 102, 0), new java.awt.Color(0, 51, 0)));
        Back3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back3MouseClicked(evt);
            }
        });
        Player3.add(Back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        Name1.setBackground(new java.awt.Color(0, 102, 102));
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name1.setText("Player1");
        Name1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 1, true));
        Name1.setOpaque(false);
        Player3.add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 120, 30));

        Name2.setBackground(new java.awt.Color(153, 204, 0));
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name2.setText("Player2");
        Name2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 1, true));
        Name2.setOpaque(false);
        Name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name2ActionPerformed(evt);
            }
        });
        Player3.add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 120, 30));

        Name3.setBackground(new java.awt.Color(255, 51, 51));
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Name3.setText("Player3");
        Name3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 51, 0), 1, true));
        Name3.setOpaque(false);
        Player3.add(Name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 280, 120, 30));

        Players3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SEPackage/Image/Player3.png"))); // NOI18N
        Player3.add(Players3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        getContentPane().add(Player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseClicked
        PlayPanel.setVisible(false);
        SettingPanel.setVisible(false);
        StartPanel.setVisible(true);
    }//GEN-LAST:event_PlayMouseClicked

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
        new HelpGUI().setVisible(true);
    }//GEN-LAST:event_HelpMouseClicked

    private void PlayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayMouseMoved
        HoverBar.setText("Start a New Game!");
    }//GEN-LAST:event_PlayMouseMoved

    private void HelpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseMoved
        HoverBar.setText("About the Game");
    }//GEN-LAST:event_HelpMouseMoved

    private void HoverBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoverBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoverBarActionPerformed

    private void HighScoreMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreMouseMoved
        HoverBar.setText("See your current High Score!");
    }//GEN-LAST:event_HighScoreMouseMoved

    private void EnterSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnterSettingMouseClicked
        StartPanel.setVisible(false);
        SettingPanel.setVisible(true);
    }//GEN-LAST:event_EnterSettingMouseClicked

    private void SnakesPositionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnakesPositionMouseClicked
        SnakeGo.setVisible(true);
        LadderGo.setVisible(false);
        SettingsBg.setVisible(false);
        SnakeBg.setVisible(true);
        HeadField.setVisible(true);
        TailField.setVisible(true);
        SnakeArea.setVisible(true);
        SnakePane.setVisible(true);
        LadderBg.setVisible(false);
        StartLadder.setVisible(false);
        EndLadder.setVisible(false);
        LadderArea.setVisible(false);
        LadderPane.setVisible(false);
        TableBg.setVisible(false);
        button5.setVisible(false);
        button12.setVisible(false);
        button11.setVisible(false);
        button10.setVisible(false);
        button9.setVisible(false);
        button8.setVisible(false);
        button7.setVisible(false);
        button6.setVisible(false);
    }//GEN-LAST:event_SnakesPositionMouseClicked

    private void LadderPositionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LadderPositionMouseClicked
        SnakeGo.setVisible(false);
        LadderGo.setVisible(true);
        SettingsBg.setVisible(false);
        SnakeBg.setVisible(false);
        HeadField.setVisible(false);
        TailField.setVisible(false);
        SnakeArea.setVisible(false);
        SnakePane.setVisible(false);
        LadderBg.setVisible(true);
        StartLadder.setVisible(true);
        EndLadder.setVisible(true);
        LadderArea.setVisible(true);
        LadderPane.setVisible(true);
        TableBg.setVisible(false);
        button5.setVisible(false);
        button12.setVisible(false);
        button11.setVisible(false);
        button10.setVisible(false);
        button9.setVisible(false);
        button8.setVisible(false);
        button7.setVisible(false);
        button6.setVisible(false);
    }//GEN-LAST:event_LadderPositionMouseClicked

    private void TableSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSizeMouseClicked
        SnakeGo.setVisible(false);
        LadderGo.setVisible(false);
        SettingsBg.setVisible(false);
        SnakeBg.setVisible(false);
        HeadField.setVisible(false);
        TailField.setVisible(false);
        SnakeArea.setVisible(false);
        SnakePane.setVisible(false);
        LadderBg.setVisible(false);
        StartLadder.setVisible(false);
        EndLadder.setVisible(false);
        LadderArea.setVisible(false);
        LadderPane.setVisible(false);
        button5.setVisible(true);
        button12.setVisible(true);
        button11.setVisible(true);
        button10.setVisible(true);
        button9.setVisible(true);
        button8.setVisible(true);
        button7.setVisible(true);
        button6.setVisible(true);
        TableBg.setVisible(true);
    }//GEN-LAST:event_TableSizeMouseClicked

    private void EndLadderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndLadderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndLadderActionPerformed

    private void LadderGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LadderGoMouseClicked
        int temp=0,temp2=0,flag=0;
        if(StartLadder.getText().equals("") && EndLadder.getText().equals(""))
        {
            new ErrorGUI().setVisible(true);//System.out.println(StartLadder.getText()+"a" +EndLadder.getText());

        }
        else
        {
            try
            {
                temp=Integer.parseInt(StartLadder.getText());
                temp2=Integer.parseInt(EndLadder.getText());

            }
            catch(Exception e)
            {
                flag=1;
                new ErrorGUI().setVisible(true);
            }
            if(flag==0)
            {
                if(temp<=choice*choice && temp2 <=choice*choice)
                {
                    cust.ladders.add(new Ladder(Integer.parseInt(EndLadder.getText()),Integer.parseInt(StartLadder.getText())));
                    LadderArea.append(StartLadder.getText()+","+EndLadder.getText()+"\n");
                }
                else
                new ErrorGUI().setVisible(true);
            }
            StartLadder.setText(null);
            EndLadder.setText(null);
        }
    }//GEN-LAST:event_LadderGoMouseClicked

    private void TailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TailFieldActionPerformed

    private void SnakeGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnakeGoMouseClicked
        int temp=0,temp2=0,flag=0;
        if(HeadField.getText().equals("") && TailField.getText().equals(""))
           new ErrorGUI().setVisible(true);
        else
        {
            try
            {
                temp=Integer.parseInt(HeadField.getText());
                temp2=Integer.parseInt(TailField.getText());

            }
            catch(Exception e)
            {
                flag=1;
                new ErrorGUI().setVisible(true);
            }
            if(flag==0)
            {
                if(temp<=choice*choice && temp2 <=choice*choice)
                {
                    cust.snakes.add(new Snake(Integer.parseInt(HeadField.getText()),Integer.parseInt(TailField.getText())));
                    SnakeArea.append(HeadField.getText()+","+TailField.getText()+"\n");
                }
                else
                new ErrorGUI().setVisible(true);
            }

            HeadField.setText(null);
            TailField.setText(null);
        }
    }//GEN-LAST:event_SnakeGoMouseClicked

    private void SnakeGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnakeGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnakeGoActionPerformed

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        button12.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,5,-1);
        cust.isCustomized=true;
        choice=5;// TODO add your handling code here:
    }//GEN-LAST:event_button5MouseClicked

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed

    }//GEN-LAST:event_button5ActionPerformed

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
        button5.setSelected(false);
        button12.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,6,-1);
        cust.isCustomized=true;
        choice=6;// TODO add your handling code here:
    }//GEN-LAST:event_button6MouseClicked

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button12.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);
        cust=new Customize(0,0,7,-1);
        choice=7;// TODO add your handling code here:
        cust.isCustomized=true;
        SnakeArea.setText(null);
        LadderArea.setText(null);
    }//GEN-LAST:event_button7MouseClicked

    private void button8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button12.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);// TODO add your handling code here:
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,8,-1);
        cust.isCustomized=true;
        choice=8;
    }//GEN-LAST:event_button8MouseClicked

    private void button9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button12.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);// TODO add your handling code here:
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,9,-1);
        cust.isCustomized=true;
        choice=9;
    }//GEN-LAST:event_button9MouseClicked

    private void button10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button10MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button12.setSelected(false);
        button11.setSelected(false);// TODO add your handling code here:
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,10,-1);
        cust.isCustomized=true;
        choice=10;
    }//GEN-LAST:event_button10MouseClicked

    private void button11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button11MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button12.setSelected(false);// TODO add your handling code here:
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,11,-1);
        cust.isCustomized=true;
        choice=11;
    }//GEN-LAST:event_button11MouseClicked

    private void button12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button12MouseClicked
        button5.setSelected(false);
        button6.setSelected(false);
        button7.setSelected(false);
        button8.setSelected(false);
        button9.setSelected(false);
        button10.setSelected(false);
        button11.setSelected(false);
        SnakeArea.setText(null);
        LadderArea.setText(null);
        cust=new Customize(0,0,12,-1);
        cust.isCustomized=true;
        choice=12;

    }//GEN-LAST:event_button12MouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        StartPanel.setVisible(true);
        PlayPanel.setVisible(false);
        SettingPanel.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseClicked

    private void Name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name2ActionPerformed

    private void StartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartButtonMouseClicked
        if(Integer.parseInt(NumberPlayers.getSelectedItem()+"")==1)
        {
            StartPanel.setVisible(false);
            Player1.setVisible(true);
        }
        else if(Integer.parseInt(NumberPlayers.getSelectedItem()+"")==2)
        {
            StartPanel.setVisible(false);
            Player2.setVisible(true);
        } 
        else
        {
            StartPanel.setVisible(false);
            Player3.setVisible(true);
        }
    }//GEN-LAST:event_StartButtonMouseClicked

    private void HighScoreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighScoreFieldActionPerformed
    String s="";
        try {
        FileReader fr = new FileReader("HighScore"); // TODO add your handling code here:
    } catch (FileNotFoundException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        s= new BufferedReader(fr).readLine();
    } catch (IOException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    if(s.compareTo("-1")==1)
        HighScore.setText("No HighScore!");
    else
        HighScore.setText(s);
    try {
        fr.close();
    } catch (IOException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_HighScoreFieldActionPerformed

    private void HighScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreMouseClicked
        HighScorePanel.setVisible(true);
        PlayPanel.setVisible(false);
        StartPanel.setVisible(false);
        SettingPanel.setVisible(false);
        Player1.setVisible(false);
        Player2.setVisible(false);
        Player3.setVisible(false);
    }//GEN-LAST:event_HighScoreMouseClicked

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        HighScorePanel.setVisible(false);
        PlayPanel.setVisible(true);
    }//GEN-LAST:event_BackMouseClicked

    private int getHighScore()
    {
        String s="";
        FileReader fr=null;
        try {
            fr = new FileReader("C:\\Users\\Rajendra\\Documents\\NetBeansProjects\\snakeladder\\HighScore.txt");
    } catch (FileNotFoundException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
        BufferedReader br=new BufferedReader(fr);
    try {
        s=br.readLine();
    } catch (IOException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    try {
        fr.close();
    } catch (IOException ex) {
        Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    return Integer.parseInt(s);
    }
    private void HighScoreFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HighScoreFieldMouseClicked
        int HighScore=getHighScore();
        if(HighScore!=-1)
            HighScoreField.setText(HighScore+"");
        else
            HighScoreField.setText("No HighScore!");
    }//GEN-LAST:event_HighScoreFieldMouseClicked

    private void Back1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back1MouseClicked
        StartPanel.setVisible(false);
        PlayPanel.setVisible(true);
    }//GEN-LAST:event_Back1MouseClicked

    private void Back2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back2MouseClicked
        Player1.setVisible(false);
        StartPanel.setVisible(true);
    }//GEN-LAST:event_Back2MouseClicked

    private void Back3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back3MouseClicked
        Player3.setVisible(false);
        StartPanel.setVisible(true);
    }//GEN-LAST:event_Back3MouseClicked

    private void Back4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back4MouseClicked
        Player2.setVisible(false);
        StartPanel.setVisible(true);
    }//GEN-LAST:event_Back4MouseClicked

    private void Player1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Player1MouseClicked

    }//GEN-LAST:event_Player1MouseClicked

    private void LadderGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LadderGoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LadderGoActionPerformed

    private void Play3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play3MouseClicked
        if(cust==null)
        {
            cust=new Customize(5,5,8,-1);
            cust.players=3;
            cust.size = 8;
            cust.snakes.add( new Snake(62,6));
            cust.ladders.add(new Ladder(64,26));
            cust.snakes.add( new Snake(45,32));
            cust.ladders.add(new Ladder(36,5));
            cust.snakes.add( new Snake(52,23));
            cust.ladders.add(new Ladder(31,17));
            cust.snakes.add( new Snake(28,2));
            cust.ladders.add(new Ladder(60,51));
            cust.snakes.add( new Snake(19,12));
            cust.ladders.add(new Ladder(47,18));
        }
        cust.players=3;
        cust.HighScore=getHighScore();
        player=new Player[3];
        player[0] = new Player(0);
        player[0].name=Name1.getText();
        player[1] = new Player(1);
        player[1].name=Name2.getText();
        player[2] = new Player(2);
        player[2].name=Name3.getText();
        try {
            this.dispose();
            new BoardGame(cust,player).setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Play3MouseClicked

    
    private void Play1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play1MouseClicked
        if(cust==null)
        {
            cust=new Customize(5,5,8,-1);
            cust.players=1;
            cust.size = 8;
            cust.snakes.add( new Snake(62,6));
            cust.ladders.add(new Ladder(64,26));
            cust.snakes.add( new Snake(45,32));
            cust.ladders.add(new Ladder(36,5));
            cust.snakes.add( new Snake(52,23));
            cust.ladders.add(new Ladder(31,17));
            cust.snakes.add( new Snake(28,2));
            cust.ladders.add(new Ladder(60,51));
            cust.snakes.add( new Snake(19,12));
            cust.ladders.add(new Ladder(47,18));
        }
        cust.players=1;
        cust.HighScore=getHighScore();
        player=new Player[1];
        player[0] = new Player(0);
        player[0].name=Players1Name1.getText();
        try {
            this.dispose();
            new BoardGame(cust,player).setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Play1MouseClicked

    private void Play2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Play2MouseClicked
        if(cust==null)
        {
            cust=new Customize(5,5,8,-1);
            cust.size = 8;
            cust.players=2;
            cust.snakes.add( new Snake(62,6));
            cust.ladders.add(new Ladder(64,26));
            cust.snakes.add( new Snake(45,32));
            cust.ladders.add(new Ladder(36,5));
            cust.snakes.add( new Snake(52,23));
            cust.ladders.add(new Ladder(31,17));
            cust.snakes.add( new Snake(28,2));
            cust.ladders.add(new Ladder(60,51));
            cust.snakes.add( new Snake(19,12));
            cust.ladders.add(new Ladder(47,18));
        }
        cust.players=2;
        cust.HighScore=getHighScore();
        player=new Player[2];
        player[0] = new Player(0);
        player[0].name=Players2Name1.getText();
        player[1] = new Player(1);
        player[1].name=Players2Name2.getText();
        try {
            new BoardGame(cust,player).setVisible(true);
            this.dispose();
        } catch (InterruptedException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Play2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
                //StartPanel.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Back1;
    private javax.swing.JButton Back2;
    private javax.swing.JButton Back3;
    private javax.swing.JButton Back4;
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel Bg;
    private javax.swing.JLabel BgPlayEnter;
    private javax.swing.JTextField EndLadder;
    private javax.swing.JButton EnterSetting;
    private javax.swing.JTextField HeadField;
    private javax.swing.JLabel Help;
    private javax.swing.JLabel HighScore;
    private javax.swing.JTextField HighScoreField;
    private javax.swing.JLabel HighScoreLabel;
    private javax.swing.JPanel HighScorePanel;
    private javax.swing.JTextField HoverBar;
    private javax.swing.JTextArea LadderArea;
    private javax.swing.JLabel LadderBg;
    private javax.swing.JButton LadderGo;
    private javax.swing.JScrollPane LadderPane;
    private javax.swing.JLabel LadderPosition;
    private javax.swing.JLabel MusicButton;
    private javax.swing.JTextField Name1;
    private javax.swing.JTextField Name2;
    private javax.swing.JTextField Name3;
    private javax.swing.JComboBox NumberPlayers;
    private javax.swing.JLabel Play;
    private javax.swing.JLabel Play1;
    private javax.swing.JLabel Play2;
    private javax.swing.JLabel Play3;
    private javax.swing.JPanel PlayPanel;
    private javax.swing.JPanel Player1;
    private javax.swing.JPanel Player2;
    private javax.swing.JPanel Player3;
    private javax.swing.JLabel Players1;
    private javax.swing.JTextField Players1Name1;
    private javax.swing.JLabel Players2;
    private javax.swing.JTextField Players2Name1;
    private javax.swing.JTextField Players2Name2;
    private javax.swing.JLabel Players3;
    private javax.swing.JPanel SettingPanel;
    private javax.swing.JLabel SettingsBg;
    private javax.swing.JTextArea SnakeArea;
    private javax.swing.JLabel SnakeBg;
    private javax.swing.JButton SnakeGo;
    private javax.swing.JScrollPane SnakePane;
    private javax.swing.JLabel SnakesPosition;
    private javax.swing.JLabel StartButton;
    private javax.swing.JTextField StartLadder;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel TableBg;
    private javax.swing.JLabel TableSize;
    private javax.swing.JTextField TailField;
    private javax.swing.JRadioButton button10;
    private javax.swing.JRadioButton button11;
    private javax.swing.JRadioButton button12;
    private javax.swing.JRadioButton button5;
    private javax.swing.JRadioButton button6;
    private javax.swing.JRadioButton button7;
    private javax.swing.JRadioButton button8;
    private javax.swing.JRadioButton button9;
    // End of variables declaration//GEN-END:variables
}
